export const Fonts = {
  'VarelaRoundRegular': 'VarelaRound-Regular',
  'LatoLight': 'Lato-Light',
  'LatoMedium': 'Lato-Regular',
  'LatoBold': 'Lato-Bold',
  'MontserratLight': 'Montserrat-Light',
  'EncodeSansRegular': 'EncodeSans-Regular',
  'EncodeSansBold': 'EncodeSans-Bold',
  'EncodeSansSemiBold': 'EncodeSans-SemiBold',
  'EncodeSansMedium': 'EncodeSans-Medium',
  'VerdanaRegular': 'VERDANA',
  'AvenirNextBold': 'AvenirNextLTPro-BoldCn',
  'AvenirNextSemiBold': 'AvenirNextLTPro-DemiCn',
  'AvenirNextMediumCn': 'AvenirNextLTPro-MediumCn',
  'AvenirNextRegularCn': 'AvenirNextLTPro-Cn',
  'AvenirNextLight': 'AvenirNextLTPro-UltLtCn',
  'AvenirNextBold': 'AvenirNextLTPro-Bold',
  'AvenirNextMedium': 'AvenirNextLTPro-Demi',
  'AvenirNextRegular': 'AvenirNextLTPro-Regular',
};